# Indexing in 1D array

In [2]:
import numpy as np 

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # first element
print(arr[2])   # third element

10
30


# Slicing in 1D array

In [7]:
# arr[start : end : step]
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
arr[::2]

[20 30 40]


array([10, 30, 50])

# Indexing in 2D arrays

In [9]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2[0, 1]       # row index: 0 ; column index: 1


np.int64(2)

# Slicing in 2D arrays

In [11]:
# get a row
print("\n",arr2[1])

# get a column
print("\n",arr2[:, 1])

# get a submatrix
print("\n",arr2[0:2, 1:3])    # Explanation: Rows: 0 to 1 ; Columns: 1 to 2

# Boolean indexing
print("\n",arr2>2)



 [4 5 6]

 [2 5 8]

 [[2 3]
 [5 6]]

 [[False False  True]
 [ True  True  True]
 [ True  True  True]]


# Indexing in 3D arrays

- A 3D array has three axes.
- The indexing pattern is:   arr[block, row, column]


In [15]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr.shape)    # (block, row, column)

# first block
print("\n",arr[0])

# second block
print("\n",arr[1])

# specific row inside block
print("\n",arr[0,1])     # block 1, row 2

# single element
print("\n",arr[1,0,1])


(2, 2, 3)

 [[1 2 3]
 [4 5 6]]

 [[ 7  8  9]
 [10 11 12]]

 [4 5 6]

 8


# Slicing in 3D arrays

- general pattern:  arr[block_range, row_range, column_range]


In [16]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

# All blocks, first row
print("\n",arr[:, 0, :])

# First block, all rows, first two columns
print("\n",arr[0, :, 0:2])

# All blocks, all rows, last two columns
print("\n",arr[:, :, 1:])

# Get first column from all blocks
print("\n",arr[:, :, 0])

# Modifying values
arr[0, 1, 2] = 99
print("\n",arr)


 [[1 2 3]
 [7 8 9]]

 [[1 2]
 [4 5]]

 [[[ 2  3]
  [ 5  6]]

 [[ 8  9]
  [11 12]]]

 [[ 1  4]
 [ 7 10]]

 [[[ 1  2  3]
  [ 4  5 99]]

 [[ 7  8  9]
  [10 11 12]]]


# NumPy Slices: Views vs Copies

A key difference between NumPy arrays and Python lists is:

> **NumPy slices are views, not copies.**

This means a slice shares the same memory as the original array. Changes to the slice will also change the original array.

## Example

```python
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 12, 12, 12, 8, 9])

arr_slice = arr[5:8]
print(arr_slice)
```

Output:

```python
[12 12 12]
```

Modify the slice:

```python
arr_slice[1] = 12345

print(arr)
```

Output:

```python
[    0     1     2     3     4    12 12345    12     8     9]
```

The original array changed because `arr_slice` is a view.

## Assigning to All Elements

```python
arr_slice[:] = 64

print(arr)
```

Output:

```python
[0 1 2 3 4 64 64 64 8 9]
```

`[:]` selects all elements in the slice.

## Creating a Copy

To create an independent array:

```python
arr_copy = arr[5:8].copy()
```

Changes to `arr_copy` will **not** affect `arr`.

## NumPy vs Python Lists

| Operation | NumPy Array | Python List |
|------------|------------|------------|
| Slice creates copy | ❌ No | ✅ Yes |
| Slice creates view | ✅ Yes | ❌ No |
| Changes affect original | ✅ Yes | ❌ No |

## Key Point

```python
arr[5:8]
```

creates a **view**.

```python
arr[5:8].copy()
```

creates a **copy**.

# Sorting

In [12]:
import numpy as np

arr = np.array([5, 2, 8, 1, 3])
sorted_arr = np.sort(arr)        # new array
print("\n",sorted_arr)

arr = np.array([5, 2, 8, 1, 3])
arr.sort()                       # Sorts original array
print("\n",arr)

# Descending order
arr = np.array([5, 2, 8, 1, 3])
desc = np.sort(arr)[::-1]
print("\n",desc)


 [1 2 3 5 8]

 [1 2 3 5 8]

 [8 5 3 2 1]


In [13]:
arr2 = np.array([
    [3, 1, 2],
    [6, 5, 4]
])

# row-wise (default)[axis = 1]
print(np.sort(arr2))

# column-wise [axis = 0]
print("\n",np.sort(arr2, axis=0))


[[1 2 3]
 [4 5 6]]

 [[3 1 2]
 [6 5 4]]


| Axis     | Meaning           |
| -------- | ----------------- |
| `axis=0` | Sort down columns |
| `axis=1` | Sort across rows  |


In [18]:
import numpy as np

arr = np.array([
    [[9, 3, 1],
     [6, 5, 2]],

    [[8, 7, 4],
     [0, 11, 10]]
])

# Default sorting (axis = -1)(columns)
print("\n",np.sort(arr))

# Sort across blocks (axis=0)
print("\n",np.sort(arr, axis=0))

# Sort across rows (axis=1)
print("\n",np.sort(arr, axis=1))

# Sort across columns (axis=2)
print("\n",np.sort(arr, axis=2))

# Sort the original array
arr.sort(axis=2)
print("\n",arr)

# Descending order
print("\n",np.sort(arr, axis=2)[:, :, ::-1])

# Get sorted indices with argsort()
print("\n",np.argsort(arr, axis=2))


 [[[ 1  3  9]
  [ 2  5  6]]

 [[ 4  7  8]
  [ 0 10 11]]]

 [[[ 8  3  1]
  [ 0  5  2]]

 [[ 9  7  4]
  [ 6 11 10]]]

 [[[ 6  3  1]
  [ 9  5  2]]

 [[ 0  7  4]
  [ 8 11 10]]]

 [[[ 1  3  9]
  [ 2  5  6]]

 [[ 4  7  8]
  [ 0 10 11]]]

 [[[ 1  3  9]
  [ 2  5  6]]

 [[ 4  7  8]
  [ 0 10 11]]]

 [[[ 9  3  1]
  [ 6  5  2]]

 [[ 8  7  4]
  [11 10  0]]]

 [[[0 1 2]
  [0 1 2]]

 [[0 1 2]
  [0 1 2]]]


| Axis     | Meaning         |
| -------- | --------------- |
| `axis=0` | Between blocks  |
| `axis=1` | Between rows    |
| `axis=2` | Between columns |


# Boolean Indexing in NumPy

This is **boolean indexing** setup. The idea is to use the `names` array to filter rows in `data`.

## The arrays

```python
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data  = np.array([[ 4,  7],   # Bob
                  [ 0,  2],   # Joe
                  [-5,  6],   # Will
                  [ 0,  0],   # Bob
                  [ 1,  2],   # Will
                  [-12, -4],  # Joe
                  [ 3,  4]])  # Joe
```

Each row in `data` corresponds to the same position in `names` — row 0 belongs to Bob, row 1 to Joe, etc.

## Boolean indexing

```python
names == "Bob"
# array([ True, False, False,  True, False, False, False])

data[names == "Bob"]
# array([[4, 7],
#        [0, 0]])
```

The boolean array acts as a **mask** — `True` keeps the row, `False` drops it.

## Why this is powerful

```python
data[names == "Joe"]                         # all Joe rows
data[names != "Bob"]                         # everyone except Bob
data[(names == "Bob") | (names == "Will")]   # Bob or Will
data[names == "Bob", 1]                      # only column 1 of Bob's rows
```

Use `&` and `|` for combining conditions (not `and`/`or` — those don't work on arrays).

## The link between arrays

`names` and `data` have the same length (7) — that's the contract. `names[i]` is the label for `data[i]`. This pattern — parallel arrays indexed together — is essentially what a pandas DataFrame formalizes into a proper data structure.

# The Python keywords and and or do not work with Boolean arrays. Use & (and) and | (or) instead.

# Filter

In [26]:
numbers = np.arange(12)
even_numbers = numbers[numbers % 2 == 0]    # such filtering is possible with numpy library
print(even_numbers)

# filter with mask
mask = numbers > 5
print("\n",numbers[mask])

indices = [0,2,4]
print("\n",numbers[indices])

[ 0  2  4  6  8 10]

 [ 6  7  8  9 10 11]

 [0 2 4]


In [ ]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

# Filtering with multiple conditions
print("\n",arr[(arr > 5) & (arr < 10)])

# Using np.where()
print("\n",np.where(arr > 6))     #(block_index, row_index, column_index)

# Filtering a specific block
print("\n",arr[0][arr[0] > 3])

# Replace values using filtering
arr[arr > 8] = 0
print("\n",arr)

# Replace values in a specific block
arr[1][arr[1] > 8] = 0
print("\n",arr)

# arr[block][condition] or
# arr[block, condition]


 [6 7 8 9]

 (array([1, 1, 1, 1, 1, 1]), array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

 [4 5 6]

 [[[1 2 3]
  [4 5 6]]

 [[7 8 0]
  [0 0 0]]]

 [[[1 2 3]
  [4 5 6]]

 [[7 8 0]
  [0 0 0]]]


# Fancy Indexing in NumPy

**Fancy Indexing** is a way of selecting elements from a NumPy array using **arrays or lists of indices** instead of slices.

---

# Basic Example

```python
import numpy as np

arr = np.arange(10)

print(arr)
```

Output:

```python
[0 1 2 3 4 5 6 7 8 9]
```

Select specific indices:

```python
print(arr[[4, 3, 0, 6]])
```

Output:

```python
[4 3 0 6]
```

NumPy returns elements at indices 4, 3, 0, and 6.

---

# Negative Indices

```python
print(arr[[-1, -3, -5]])
```

Output:

```python
[9 7 5]
```

Negative indices count from the end of the array.

---

# Fancy Indexing with 2D Arrays

```python
arr = np.arange(32).reshape((8, 4))

print(arr)
```

Output:

```python
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
```

Select rows:

```python
print(arr[[4, 3, 0, 6]])
```

Output:

```python
[[16 17 18 19]
 [12 13 14 15]
 [ 0  1  2  3]
 [24 25 26 27]]
```

Rows are returned in the order specified.

---

# Selecting Rows and Columns

```python
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
```

Output:

```python
[ 4 23 29 10]
```

Explanation:

| Row | Column | Value |
|------|---------|--------|
| 1 | 0 | 4 |
| 5 | 3 | 23 |
| 7 | 1 | 29 |
| 2 | 2 | 10 |

NumPy pairs corresponding row and column indices.

---

# Using np.ix_()

To select multiple rows and columns together:

```python
print(arr[np.ix_([1, 5, 7], [0, 2, 3])])
```

Output:

```python
[[ 4  6  7]
 [20 22 23]
 [28 30 31]]
```

Selected:
- Rows: 1, 5, 7
- Columns: 0, 2, 3

---

# Important: Fancy Indexing Creates Copies

Unlike slicing, fancy indexing creates a **copy**, not a view.

```python
arr = np.arange(10)

result = arr[[1, 3, 5]]

result[0] = 100

print(arr)
```

Output:

```python
[0 1 2 3 4 5 6 7 8 9]
```

The original array is unchanged.

---

# Slicing vs Fancy Indexing

| Feature | Slicing | Fancy Indexing |
|----------|----------|----------|
| Uses ranges | ✅ | ❌ |
| Uses index lists | ❌ | ✅ |
| Returns view | ✅ | ❌ |
| Returns copy | ❌ | ✅ |

---

# Summary

- Fancy indexing uses lists or arrays of indices.
- Allows selecting elements in any order.
- Works with 1D and multidimensional arrays.
- Returns a **copy**, not a view.
- Useful for selecting specific rows, columns, or elements.

# Fancy Indexing — Two-step vs `np.ix_`

```python
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]       # two-step
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]  # one-step
```

Same result, different approach.

## What the two-step does

```python
arr[[1, 5, 7, 2]]           # step 1: select rows → shape (4, 4)
             [:, [0,3,1,2]] # step 2: reorder columns of result
```

First pulls the rows out, then fancy-indexes the columns on the intermediate result.

## Why `np.ix_` is better

```python
# two-step creates an intermediate array (wasted memory)
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

# np.ix_ does it in one indexing operation
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]
```

For large arrays the intermediate copy in the two-step approach costs extra memory.
`np.ix_` constructs the full index in one shot — no temporary array.
Both return **copies** either way — fancy indexing never returns a view.

# Matrix Multiplication with `np.dot`

`np.dot` computes the **inner matrix product** (matrix multiplication).

## Basic rule

For two 2D arrays, `np.dot(A, B)` requires the **inner dimensions to match**:

```
A shape: (m, n)
B shape: (n, k)
result:  (m, k)
```

The `n` must be the same — that's the "inner" dimension.

## Example

```python
A = np.array([[1, 2, 3],   # shape (2, 3)
              [4, 5, 6]])

B = np.array([[1, 0],      # shape (3, 2)
              [0, 1],
              [1, 0]])

np.dot(A, B)               # shape (2, 2)
# array([[ 4,  2],
#        [10,  5]])
```

## How each element is computed

Each output element is the **dot product of a row from A and a column from B**:

```
result[0, 0] = A[0] · B[:, 0] = 1*1 + 2*0 + 3*1 = 4
result[0, 1] = A[0] · B[:, 1] = 1*0 + 2*1 + 3*0 = 2
```

## Three ways to write it

```python
np.dot(A, B)    # function form
A.dot(B)        # method form
A @ B           # operator form — preferred in modern NumPy
```

`@` was introduced in Python 3.5 / NumPy 1.10 and is now the standard.

## Common shapes

| A | B | result | meaning |
|---|---|---|---|
| `(m, n)` | `(n, k)` | `(m, k)` | matrix × matrix |
| `(m, n)` | `(n,)` | `(m,)` | matrix × vector |
| `(n,)` | `(n,)` | scalar | dot product |

## `*` vs `@`

```python
A * B    # elementwise multiply — shapes must match exactly
A @ B    # matrix multiply — inner dims must match
```

Common mistake — `*` does NOT do matrix multiplication in NumPy.

### arr.T @ arr   # equivalent to np.dot(arr.T, arr)

## Swapping Axes with `swapaxes()`

Simple transposing with `.T` is a special case of swapping axes. An `ndarray` has the method `swapaxes()`, which takes a pair of axis numbers and switches the indicated axes to rearrange the data.

### Example

```python
arr
```

Output:

```python
array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])
```

```python
arr.swapaxes(0, 1)
```

Output:

```python
array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])
```

### Key Point

- `swapaxes(axis1, axis2)` exchanges the specified axes of an array.
- For a 2D array, `swapaxes(0, 1)` produces the same result as `.T` (transpose).
- Unlike copying data, axis swapping returns a view whenever possible.