## Pseudorandom Number Generation

The `numpy.random` module extends Python’s built-in `random` module with functions for efficiently generating entire arrays of sample values from many probability distributions.

### Generating Random Samples

For example, a `4 × 4` array of samples from the standard normal distribution can be generated using `numpy.random.standard_normal()`:

```python
samples = np.random.standard_normal(size=(4, 4))
samples
```

Output:

```python
array([[-0.2047,  0.4789, -0.5194, -0.5557],
       [ 1.9658,  1.3934,  0.0929,  0.2817],
       [ 0.7690,  1.2464,  1.0072, -1.2962],
       [ 0.2750,  0.2289,  1.3529,  0.8864]])
```

### NumPy vs Python `random`

Python’s built-in `random` module generates one value at a time, whereas NumPy can generate large arrays much more efficiently.

```python
from random import normalvariate

N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
```

Output:

```text
1.04 s ± 11.4 ms per loop
```

```python
%timeit np.random.standard_normal(N)
```

Output:

```text
21.9 ms ± 155 µs per loop
```

### Pseudorandom Numbers

The generated numbers are **pseudorandom**, meaning they are not truly random. Instead, they are produced by a deterministic random number generator whose behavior depends on its internal state.

### Using an Explicit Random Generator

NumPy allows creating a dedicated random number generator using `default_rng()`:

```python
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
```

The `seed` initializes the generator's state. Each call changes the state, producing a new sequence of values.

### Generator Type

```python
type(rng)
```

Output:

```python
numpy.random._generator.Generator
```

### Key Points

- `numpy.random` efficiently generates large arrays of random values.
- It is significantly faster than Python’s built-in `random` module.
- Generated values are **pseudorandom**, not truly random.
- `default_rng(seed)` creates an independent random number generator.
- Using the same seed produces the same sequence of random numbers, which is useful for reproducibility.

## Universal Functions: Fast Element-Wise Array Functions

A **universal function (ufunc)** is a function that performs element-wise operations on NumPy arrays (`ndarray`). Ufuncs are fast, vectorized versions of functions that operate on scalar values.

### Unary Ufuncs

Unary ufuncs operate on a single array and return a new array.

#### Example: `np.sqrt()`

```python
arr = np.arange(10)
arr
```

Output:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

```python
np.sqrt(arr)
```

Output:

```python
array([0.    , 1.    , 1.4142, 1.7321, 2.    ,
       2.2361, 2.4495, 2.6458, 2.8284, 3.    ])
```

#### Example: `np.exp()`

```python
np.exp(arr)
```

Output:

```python
array([1.0000, 2.7183, 7.3891, 20.0855, 54.5982,
       148.4132, 403.4288, 1096.6332, 2980.9580, 8103.0839])
```

### Binary Ufuncs

Binary ufuncs operate on two arrays and return a result array.

#### Example: `np.maximum()`

```python
x = rng.standard_normal(8)
y = rng.standard_normal(8)

x
```

Output:

```python
array([-1.3678,  0.6489,  0.3611, -1.9529,
        2.3474,  0.9685, -0.7594,  0.9022])
```

```python
y
```

Output:

```python
array([-0.4670, -0.0607,  0.7888, -1.2567,
        0.5759,  1.3990,  1.3223, -0.2997])
```

```python
np.maximum(x, y)
```

Output:

```python
array([-0.4670,  0.6489,  0.7888, -1.2567,
        2.3474,  1.3990,  1.3223,  0.9022])
```

`np.maximum()` computes the element-wise maximum between corresponding elements of two arrays.

### Ufuncs Returning Multiple Arrays

Some ufuncs return more than one array. One example is `np.modf()`, which separates the fractional and integral parts of floating-point numbers.

```python
arr = rng.standard_normal(7) * 5
arr
```

Output:

```python
array([ 4.5146, -8.1079, -0.7909,  2.2474,
       -6.7180, -0.4084,  8.6237])
```

```python
remainder, whole_part = np.modf(arr)
```

#### Fractional Part

```python
remainder
```

Output:

```python
array([ 0.5146, -0.1079, -0.7909,  0.2474,
       -0.7180, -0.4084,  0.6237])
```

#### Integral Part

```python
whole_part
```

Output:

```python
array([ 4., -8., -0.,  2., -6., -0.,  8.])
```

### Using the `out` Parameter

Ufuncs support an optional `out` parameter that stores the result in an existing array instead of creating a new one.

```python
arr
```

Output:

```python
array([ 4.5146, -8.1079, -0.7909,  2.2474,
       -6.7180, -0.4084,  8.6237])
```

```python
out = np.zeros_like(arr)
```

```python
np.add(arr, 1)
```

Output:

```python
array([ 5.5146, -7.1079,  0.2091,  3.2474,
       -5.7180,  0.5916,  9.6237])
```

```python
np.add(arr, 1, out=out)
```

Output:

```python
array([ 5.5146, -7.1079,  0.2091,  3.2474,
       -5.7180,  0.5916,  9.6237])
```

```python
out
```

Output:

```python
array([ 5.5146, -7.1079,  0.2091,  3.2474,
       -5.7180,  0.5916,  9.6237])
```

### Key Points

- **Ufuncs** perform fast element-wise operations on NumPy arrays.
- **Unary ufuncs** operate on one array (e.g., `np.sqrt`, `np.exp`).
- **Binary ufuncs** operate on two arrays (e.g., `np.add`, `np.maximum`).
- Some ufuncs can return **multiple arrays** (e.g., `np.modf`).
- The **`out` parameter** allows storing results in an existing array to avoid extra memory allocation.
- Ufuncs are highly optimized and significantly faster than Python loops.