## Vectorization

Using NumPy arrays enables you to express many data-processing tasks as concise array expressions that might otherwise require writing explicit loops.

This practice of replacing explicit loops with array expressions is called **vectorization**.

### Example

Without vectorization:

```python
result = []
for x in arr:
    result.append(x * 2)
```

With vectorization:

```python
result = arr * 2
```

### Benefits of Vectorization

- Produces shorter and more readable code.
- Eliminates the need for explicit Python loops.
- Executes much faster than pure Python implementations.
- Particularly effective for numerical computations on large datasets.

### Key Point

Vectorized array operations leverage NumPy's optimized C-based implementation, making them significantly faster than equivalent operations written using Python loops.

## `numpy.meshgrid()`

The `numpy.meshgrid()` function creates coordinate matrices from coordinate vectors. It is commonly used for evaluating functions on a grid and for plotting 2D or 3D surfaces.

### Syntax

```python
numpy.meshgrid(*xi, copy=True, sparse=False, indexing='xy')
```

### Example

```python
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5])

X, Y = np.meshgrid(x, y)

print(X)
print(Y)
```

Output:

```python
X =
[[1 2 3]
 [1 2 3]]

Y =
[[4 4 4]
 [5 5 5]]
```

### Visualization

Input vectors:

```text
x = [1, 2, 3]
y = [4, 5]
```

Generated grids:

```text
X =                 Y =
[[1 2 3]            [[4 4 4]
 [1 2 3]]            [5 5 5]]
```

Each position `(X[i, j], Y[i, j])` represents a coordinate pair:

```text
(1,4) (2,4) (3,4)
(1,5) (2,5) (3,5)
```

### Using the Grid

```python
Z = X + Y
print(Z)
```

Output:

```python
[[5 6 7]
 [6 7 8]]
```

### Common Use Cases

- Creating coordinate grids
- Surface and contour plots
- Mathematical function evaluation
- Simulations and numerical computations

### Key Points

- `meshgrid()` converts 1D coordinate arrays into coordinate matrices.
- Returns one array for each input vector.
- Useful for working with functions of multiple variables.
- Widely used with NumPy and Matplotlib for visualization.

## Understanding `numpy.meshgrid()`

Suppose you have two 1D arrays representing the x-axis and y-axis, and you want to evaluate a function `f(x, y)` at every possible combination of x and y values.

### Input Arrays

```python
x = [1, 2, 3]
y = [10, 20, 30]
```

All possible coordinate pairs:

```text
(1,10) (2,10) (3,10)
(1,20) (2,20) (3,20)
(1,30) (2,30) (3,30)
```

This forms a **3 × 3 grid** containing **9 points**.

### What `meshgrid()` Produces

```python
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

xs, ys = np.meshgrid(x, y)
```

#### `xs` — x-coordinate at every grid point

```python
xs = [[1, 2, 3],
      [1, 2, 3],
      [1, 2, 3]]
```

- Row 0 → `y = 10`, x varies
- Row 1 → `y = 20`, x varies
- Row 2 → `y = 30`, x varies

#### `ys` — y-coordinate at every grid point

```python
ys = [[10, 10, 10],
      [20, 20, 20],
      [30, 30, 30]]
```

- Row 0 → `y = 10` everywhere
- Row 1 → `y = 20` everywhere
- Row 2 → `y = 30` everywhere

### Accessing a Grid Point

```python
xs[1, 2]  # 3
ys[1, 2]  # 20
```

Therefore, the coordinate at row 1, column 2 is:

```text
(3, 20)
```

### Why These Shapes?

- `xs` repeats x-values across rows.
- `ys` repeats y-values down columns.

This means:

- Moving horizontally (across columns) changes **x**.
- Moving vertically (across rows) changes **y**.

### Visual Representation

```text
y = 30   •   •   •
y = 20   •   •   •
y = 10   •   •   •
          x=1 x=2 x=3
```

Each dot corresponds to a coordinate pair `(x, y)`.

### Evaluating a Function on the Grid

```python
z = xs + ys
```

Result:

```python
array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])
```

Every element is computed as:

```text
z[i, j] = xs[i, j] + ys[i, j]
```

### Key Point

`meshgrid()` converts 1D coordinate arrays into 2D coordinate matrices, allowing you to evaluate functions over an entire grid without writing loops.

## Expressing Conditional Logic as Array Operations

The `numpy.where()` function is a vectorized version of the Python ternary expression:

```python
x if condition else y
```

It allows you to apply conditional logic to entire arrays without using loops.

### Example Data

```python
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])
```

### Using a List Comprehension

One way to select values based on the condition is:

```python
result = [
    (x if c else y)
    for x, y, c in zip(xarr, yarr, cond)
]
```

Output:

```python
[1.1, 2.2, 1.3, 1.4, 2.5]
```

#### Drawbacks

- Slow for large arrays because it runs in Python.
- Does not work naturally with multidimensional arrays.
- Less concise than NumPy operations.

### Using `np.where()`

The same operation can be performed efficiently with a single function call:

```python
result = np.where(cond, xarr, yarr)
result
```

Output:

```python
array([1.1, 2.2, 1.3, 1.4, 2.5])
```

### How It Works

```python
np.where(condition, value_if_true, value_if_false)
```

For each position:

```text
If condition is True  → take value from xarr
If condition is False → take value from yarr
```

| Condition | xarr | yarr | Result |
|-----------|------|------|--------|
| True  | 1.1 | 2.1 | 1.1 |
| False | 1.2 | 2.2 | 2.2 |
| True  | 1.3 | 2.3 | 1.3 |
| True  | 1.4 | 2.4 | 1.4 |
| False | 1.5 | 2.5 | 2.5 |

### Using Scalars

The second and third arguments do not have to be arrays.

```python
arr = np.array([-2, -1, 0, 1, 2])

np.where(arr > 0, 1, 0)
```

Output:

```python
array([0, 0, 0, 1, 1])
```

This creates a new array where:

- Positive values become `1`
- Non-positive values become `0`

### Common Data Analysis Use Cases

#### Replace Negative Values

```python
arr = np.array([-3, -1, 2, 4])

np.where(arr < 0, 0, arr)
```

Output:

```python
array([0, 0, 2, 4])
```

#### Categorize Data

```python
scores = np.array([45, 80, 60, 90])

grades = np.where(scores >= 60, "Pass", "Fail")
```

Output:

```python
array(['Fail', 'Pass', 'Pass', 'Pass'])
```

### Key Points

- `np.where()` is a vectorized alternative to `x if condition else y`.
- Works efficiently on entire arrays.
- Supports multidimensional arrays.
- Can use arrays, scalars, or a combination of both.
- Commonly used for filtering, replacing, and categorizing data.

## Mathematical and Statistical Methods

NumPy provides many mathematical and statistical functions that operate on entire arrays or along a specific axis.

Common aggregation (reduction) methods include:

- `sum()`
- `mean()`
- `std()` (standard deviation)
- `min()`
- `max()`

These can be called either as:

- Array methods (`arr.mean()`)
- NumPy functions (`np.mean(arr)`)

### Example Array

```python
arr = rng.standard_normal((5, 4))

arr
```

Output:

```python
array([[-1.1082,  0.1360,  1.3471,  0.0611],
       [ 0.0709,  0.4337,  0.2775,  0.5303],
       [ 0.5367,  0.6184, -0.7950,  0.3000],
       [-1.6027,  0.2668, -1.2616, -0.0713],
       [ 0.4740, -0.4149,  0.0977, -1.6404]])
```

### Mean

Using the array method:

```python
arr.mean()
```

Output:

```python
-0.08719744457434529
```

Using the NumPy function:

```python
np.mean(arr)
```

Output:

```python
-0.08719744457434529
```

### Sum

```python
arr.sum()
```

Output:

```python
-1.743948891486906
```

### Aggregation Along an Axis

Many statistical methods accept an `axis` argument.

#### Row-wise Mean (`axis=1`)

```python
arr.mean(axis=1)
```

Output:

```python
array([ 0.1090,
        0.3281,
        0.1650,
       -0.6672,
       -0.3709])
```

Each value is the mean of one row.

#### Column-wise Sum (`axis=0`)

```python
arr.sum(axis=0)
```

Output:

```python
array([-1.6292,
        1.0399,
       -0.3344,
       -0.8203])
```

Each value is the sum of one column.

### Understanding `axis`

For a 2D array:

```text
axis=0 → Down rows (column operation)

[
 [1, 2],
 [3, 4],
 [5, 6]
]
```

```text
Result: [9, 12]
```

```text
axis=1 → Across columns (row operation)

[
 [1, 2],
 [3, 4],
 [5, 6]
]
```

```text
Result: [3, 7, 11]
```

### Cumulative Operations

Unlike aggregations, cumulative methods return intermediate results instead of a single value.

#### `cumsum()`

```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

arr.cumsum()
```

Output:

```python
array([ 0,  1,  3,  6, 10, 15, 21, 28])
```

Computation:

```text
0
0 + 1 = 1
1 + 2 = 3
3 + 3 = 6
6 + 4 = 10
10 + 5 = 15
15 + 6 = 21
21 + 7 = 28
```

#### `cumprod()`

```python
arr = np.array([1, 2, 3, 4])

arr.cumprod()
```

Output:

```python
array([ 1,  2,  6, 24])
```

Computation:

```text
1
1 × 2 = 2
2 × 3 = 6
6 × 4 = 24
```

### Common Statistical Methods

| Method | Description |
|----------|-------------|
| `sum()` | Sum of elements |
| `mean()` | Average value |
| `std()` | Standard deviation |
| `var()` | Variance |
| `min()` | Minimum value |
| `max()` | Maximum value |
| `argmin()` | Index of minimum value |
| `argmax()` | Index of maximum value |
| `cumsum()` | Cumulative sum |
| `cumprod()` | Cumulative product |

### Key Points

- Aggregation methods reduce an array to summary statistics.
- Methods can operate on the entire array or along a specified axis.
- `axis=0` performs column-wise operations.
- `axis=1` performs row-wise operations.
- `cumsum()` and `cumprod()` return intermediate cumulative results rather than a single aggregated value.

## Methods for Boolean Arrays

In NumPy, Boolean values are automatically converted to:

- `True` → `1`
- `False` → `0`

Because of this, aggregation methods such as `sum()` can be used to count the number of `True` values in a Boolean array.

### Counting True Values

```python
arr = rng.standard_normal(100)
```

Count positive values:

```python
(arr > 0).sum()
```

Output:

```python
48
```

Count non-positive values:

```python
(arr <= 0).sum()
```

Output:

```python
52
```

### Why Parentheses Are Needed

```python
(arr > 0).sum()
```

The comparison:

```python
arr > 0
```

creates a temporary Boolean array:

```python
[True, False, True, ...]
```

Parentheses are required so that `.sum()` is applied to the Boolean array rather than to `0`.

### Example

```python
arr = np.array([-2, 1, 3, -1, 5])

arr > 0
```

Output:

```python
array([False, True, True, False, True])
```

```python
(arr > 0).sum()
```

Output:

```python
3
```

There are three positive values in the array.

---

## `any()` and `all()`

NumPy provides two useful methods for working with Boolean arrays:

### `any()`

Returns `True` if **at least one** element is `True`.

```python
bools = np.array([False, False, True, False])

bools.any()
```

Output:

```python
True
```

Since one value is `True`, the result is `True`.

### `all()`

Returns `True` only if **every** element is `True`.

```python
bools.all()
```

Output:

```python
False
```

Since not all values are `True`, the result is `False`.

### Example

```python
arr = np.array([True, True, True])

arr.any()
```

Output:

```python
True
```

```python
arr.all()
```

Output:

```python
True
```

---

## Working with Non-Boolean Arrays

`any()` and `all()` also work with non-Boolean arrays.

In this case:

- `0` is treated as `False`
- Nonzero values are treated as `True`

### Example: `any()`

```python
arr = np.array([0, 0, 5, 0])

arr.any()
```

Output:

```python
True
```

Because at least one element (`5`) is nonzero.

### Example: `all()`

```python
arr = np.array([1, 2, 3, 4])

arr.all()
```

Output:

```python
True
```

All elements are nonzero.

```python
arr = np.array([1, 2, 0, 4])

arr.all()
```

Output:

```python
False
```

Because the array contains a `0`.

---

## Summary

| Method | Description |
|----------|-------------|
| `(condition).sum()` | Counts the number of `True` values |
| `any()` | Returns `True` if at least one element is `True` |
| `all()` | Returns `True` if every element is `True` |

### Key Points

- `True` is treated as `1` and `False` as `0`.
- `sum()` can be used to count matching values.
- `any()` checks whether at least one element is true.
- `all()` checks whether every element is true.
- For non-Boolean arrays, nonzero values are treated as `True`.

## Unique and Other Set Logic

NumPy provides several set operations for one-dimensional arrays (`ndarray`). These functions are useful for finding unique values, checking membership, and performing other set-related operations.

---

## `np.unique()`

The `np.unique()` function returns the **sorted unique values** in an array.

### Example with Strings

```python
names = np.array([
    "Bob", "Will", "Joe",
    "Bob", "Will", "Joe", "Joe"
])

np.unique(names)
```

Output:

```python
array(['Bob', 'Joe', 'Will'], dtype='<U4')
```

Duplicate values are removed, and the result is sorted.

### Example with Numbers

```python
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

np.unique(ints)
```

Output:

```python
array([1, 2, 3, 4])
```

---

## Pure Python Alternative

The equivalent operation in pure Python is:

```python
sorted(set(names))
```

Output:

```python
['Bob', 'Joe', 'Will']
```

### Comparison

| NumPy | Python |
|---------|---------|
| `np.unique(arr)` | `sorted(set(arr))` |
| Returns NumPy array | Returns Python list |
| Optimized for arrays | General-purpose |

---

## `np.in1d()`

The `np.in1d()` function tests whether each element of one array exists in another array.

### Syntax

```python
np.in1d(array, test_values)
```

Returns a Boolean array of the same length as `array`.

### Example

```python
values = np.array([6, 0, 0, 3, 2, 5, 6])

np.in1d(values, [2, 3, 6])
```

Output:

```python
array([ True, False, False, True,
        True, False, True])
```

### Interpretation

| Value | In [2, 3, 6]? |
|---------|-------------|
| 6 | True |
| 0 | False |
| 0 | False |
| 3 | True |
| 2 | True |
| 5 | False |
| 6 | True |

---

## Practical Example

Filter only the values that belong to a given set:

```python
values = np.array([6, 0, 0, 3, 2, 5, 6])

mask = np.in1d(values, [2, 3, 6])

values[mask]
```

Output:

```python
array([6, 3, 2, 6])
```

---

## Common NumPy Set Functions

| Function | Description |
|-----------|-------------|
| `np.unique()` | Sorted unique values |
| `np.in1d()` | Membership test |
| `np.intersect1d()` | Common elements of two arrays |
| `np.union1d()` | Union of two arrays |
| `np.setdiff1d()` | Elements in first array but not second |
| `np.setxor1d()` | Elements in either array, but not both |

### Example: Intersection

```python
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

np.intersect1d(a, b)
```

Output:

```python
array([3, 4])
```

### Example: Union

```python
np.union1d(a, b)
```

Output:

```python
array([1, 2, 3, 4, 5, 6])
```

---

## Key Points

- `np.unique()` returns sorted unique elements from an array.
- `np.in1d()` checks whether each element belongs to another array.
- NumPy provides several efficient set operations for arrays.
- These functions are useful for filtering, data cleaning, and membership testing.