# What numpy(numerical Python) is used for:
- Working with arrays and matrices
- Performing mathematical operations
- Building machine learning and data science projects
- Scientific computing and simulations




# Why NumPy uses C
Python is slower for heavy math operations.
- So NumPy:
    - Takes your Python code
    - Sends the heavy calculations to C functions
    - Returns the result to Python


### Numpy arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this vectorization

# creating array from list

In [2]:
import numpy as np 

In [7]:
# 1d array
arr_1d = np.array([1,2,3]) # array takes only list as argument.
print(arr_1d)

# 2d array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


# List vs Numpy Array

In [ ]:
py_list = [1,2,3,4]
print("Python List multiplication:",py_list * 2)

np_array = np.array([1,2,3,4])
print("Python array multiplication:",np_array * 2)   #element-wise multiplication

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time:",time.time()-start)

start = time.time()
np_array = np.arange(1000000) * 2   # 2 is a scalar
print("Numpy operation time:",time.time()-start)

Python List multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication: [2 4 6 8]
List operation time: 0.055500030517578125
Array operation time: 0.002412080764770508


# Creating array from scratch

In [ ]:
# zeros array

z1 = np.zeros(5)        # 5 columns  
print(z1)
z2 = np.zeros((2,3))    # 2 rows and 3 colums
print(z2)
z3 = np.zeros((2,3,4))  # 2 arrays with 3 rows and 4 columns
print(z3)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# ones array

ones_array = np.ones((2,4))
print(o1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# creating an array with specific value

full_array = np.full((2,3),5)    # an array with 2 rows and 3 columns and all elements as 5
print(full_array)

[[5 5 5]
 [5 5 5]]


In [20]:
# range

ran1 = np.arange(0,10)
print(ran1)
ran2 = np.arange(2,10,2)   #(start,stop,step)
print(ran2)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


- np.array(range()) vs np.arange():
    - arange() stores each individual value of an array, range() stores only 3 values (start, stop, step)
    - arange() takes more space than range()
    - arange() allows floating-point numbers in step parameter, making it more flexible

In [ ]:
# evenly spaced numbers

even = np.linspace(0,1,5)
print(even)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
# random arrays (np.random.*())

rand1 = np.random.random((2,3))
print(rand1)
rand2 = np.random.randint(1,10,(2,3))
print(rand2)

[[0.70000685 0.45494224 0.92579263]
 [0.6326623  0.28353111 0.66453432]]
[[6 6 7]
 [7 6 6]]


# Vector, Matrix and Tensor

| Type   | Dimensions | Example shape | Real-world idea   |
| ------ | ---------- | ------------- | ----------------- |
| Vector | 1D         | `(4,)`        | List of numbers   |
| Matrix | 2D         | `(2,3)`       | Table/spreadsheet |
| Tensor | 3D+        | `(2,3,4)`     | Stack of tables   |


In [8]:
vector = np.array([1,2,3])
print("\n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("\n",matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n",tensor)


 [1 2 3]

 [[1 2 3]
 [4 5 6]]

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Properties of array

In [9]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# shape
print("\nShape:",arr.shape)        # 2 rows 3 columns

# dimension
print("\nDimension:",arr.ndim)     # 2D array

# size (no. of elements)
print("\nSize:",arr.size)          # 6 elements

# Data type
print("\ndtype:",arr.dtype)        # experiment with different data-types however its better to keep array's homogeneous

# Itemsize (size of elements is bytes)
print("\nItem-size:",arr.itemsize)

# nbytes (total memory taken by array)
print("\nnbytes:",arr.nbytes)      # size x itemsize

# Transpose
print("\nTranspose:",arr.T)


Shape: (2, 3)

Dimension: 2

Size: 6

dtype: int64

Item-size: 8

nbytes: 48

Transpose: [[1 4]
 [2 5]
 [3 6]]


## Array Reshaping

- Reshape

    -6 elements → can reshape into:
        - (2,3) ✔
        - (3,2) ✔
        - (6,1) ✔
        - (4,2) ✘ (needs 8 elements)


In [ ]:
#reshape
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)


[[1 2 3]
 [4 5 6]]


- Using -1 (automatic dimension)

In [ ]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(2, -1)        # prints last line because in jupiter notebook


array([[1, 2, 3],
       [4, 5, 6]])

- resize

In [14]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr.resize((3,2))
print(arr)


[[1 2]
 [3 4]
 [5 6]]


- flatten

In [15]:
#flatten
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr.flatten

<function ndarray.flatten(order='C')>

- ravel

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

r = arr.ravel()     # returns view instead of copy
print(r)


[1 2 3 4 5 6]


| Feature               | `reshape()`     | `flatten()`     | `ravel()`       | `resize()`               |
| --------------------- | --------------- | --------------- | --------------- | ------------------------ |
| Purpose               | Change shape    | Make 1D copy    | Make 1D view    | Change shape of original |
| Returns copy?         | Usually no      | Yes             | No (usually)    | No                       |
| Affects original?     | No              | No              | Yes (sometimes) | Yes                      |
| Adds zeros if bigger? | No              | No              | No              | Yes                      |
| Common use            | ML data shaping | Safe flattening | Fast flattening | In-place resizing        |


In [ ]:
#Can check time taken to run code like this in jupiter

my_arr = np.arange(1_000_000)
%timeit my_arr2 = my_arr * 2

### D-type

# NumPy Data Types Reference Table

| Data Type | Type Code | Size | Description | Example Values |
|------------|------------|------|-------------|---------------|
| int8 | i1 | 1 byte | Signed 8-bit integer | -128 to 127 |
| uint8 | u1 | 1 byte | Unsigned 8-bit integer | 0 to 255 |
| int16 | i2 | 2 bytes | Signed 16-bit integer | -32,768 to 32,767 |
| uint16 | u2 | 2 bytes | Unsigned 16-bit integer | 0 to 65,535 |
| int32 | i4 | 4 bytes | Signed 32-bit integer | Large whole numbers |
| uint32 | u4 | 4 bytes | Unsigned 32-bit integer | Large positive whole numbers |
| int64 | i8 | 8 bytes | Signed 64-bit integer | Very large whole numbers |
| uint64 | u8 | 8 bytes | Unsigned 64-bit integer | Very large positive whole numbers |
| float16 | f2 | 2 bytes | Half-precision floating point | 3.14 |
| float32 | f4 or f | 4 bytes | Single-precision floating point | 3.1415926 |
| float64 | f8 or d | 8 bytes | Double-precision floating point (default float) | 3.141592653589793 |
| float128 | f16 or g | 16 bytes | Extended-precision floating point | High-precision decimals |
| complex64 | c8 | 8 bytes | Complex number using two float32 values | 1 + 2j |
| complex128 | c16 | 16 bytes | Complex number using two float64 values | 1 + 2j |
| complex256 | c32 | 32 bytes | Complex number using two float128 values | 1 + 2j |
| bool | ? | 1 byte | Boolean values | True, False |
| object | O | Variable | Stores any Python object | Lists, dictionaries, strings |
| string_ | S | Fixed length | ASCII string type | 'S10' |
| unicode_ | U | Fixed length | Unicode string type | 'U10' |

## Quick Memory Comparison

| Type | Memory Used |
|--------|------------|
| int8 | 1 byte |
| int16 | 2 bytes |
| int32 | 4 bytes |
| int64 | 8 bytes |
| float16 | 2 bytes |
| float32 | 4 bytes |
| float64 | 8 bytes |
| bool | 1 byte |

## Commonly Used Data Types in Data Science

| Data Type | Typical Usage |
|------------|--------------|
| int32 / int64 | Integer data |
| float32 | Machine Learning and Deep Learning |
| float64 | Scientific Computing and Statistics |
| bool | Filtering and Conditions |
| object | Mixed data types |
| unicode_ | Text data |
| complex128 | Scientific and Engineering calculations |
